#!/bin/bash

# Check for environment var
if [[ -z "${RPI_ADDR}" ]]; then
    echo "ERROR:"
    echo "    Environment RPI_ADDR is not defined, please set it to the IP of the Rasbperry Pi."
    echo "    You can do this using: export RPI_ADDR=[ip]"
    exit 0
fi

# Get directory of script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# The project directory is one back from the script directory
PROJECT_DIR="${SCRIPT_DIR}/.."

# Move into the project directory
cd $PROJECT_DIR

# Zip the src folder
echo ""
echo "Zipping the project..."
tar -zcf deploy.tar.gz src

# Upload the tarball to the pi in the project directory
echo ""
echo "Uploading it to the robot..."
scp deploy.tar.gz pi@${RPI_ADDR}:/home/pi/GeorgeBot

# Remove tarball from local dir
echo ""
echo "Cleaning up..."
rm deploy.tar.gz

# This part depends on the pi having a receiving script
# Run the receive end of the deploy script through ssh on the pi
ssh pi@${RPI_ADDR} 'bash -s < /home/pi/GeorgeBot/scripts/receive'
